name: leap_ledger_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: "3.24.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  drag_and_drop_lists: ^0.4.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.6
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  meta: ^1.10.0
  path_provider: ^2.1.0
  uuid: ^4.4.0
  timezone: ^0.9.3
  url_launcher: ^6.2.6
  auto_size_text: ^3.0.0
  flutter_timezone: ^3.0.1
  device_info_plus: ^10.1.2
  web_socket_channel: ^3.0.1
  flutter_slidable: ^3.1.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:

  uses-material-design: true
  assets:
      - assets/
