name: Develop Build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1

      - name: Run flutter doctor
        run: flutter doctor

      - name: Run flutter clean
        run: flutter clean

      - name: Build APK (Unsigned)
        run: |
          flutter build apk --release \
            --dart-define=config.server.network.host=${{ vars.SERVER_HOST }} \
            --dart-define=config.server.network.port=${{ vars.SERVER_PORT }} \
            --dart-define=config.server.signKey=${{ secrets.SERVER_SIGN_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LeapLedger.apk
          path: build/app/outputs/flutter-apk/app-release.apk